"""empty message

Revision ID: 25b53cbb2d39
Revises: 3df8a99f3252
Create Date: 2022-02-12 23:10:58.156273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25b53cbb2d39'
down_revision = '3df8a99f3252'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cities', sa.Column('ready_for_updates', sa.Boolean(), nullable=True))
    op.drop_column('cities', 'ready_to_updates')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cities', sa.Column('ready_to_updates', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('cities', 'ready_for_updates')
    # ### end Alembic commands ###
