"""empty message

Revision ID: 27942604c57d
Revises: b7340a6c3ecf
Create Date: 2022-01-12 01:15:41.362818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27942604c57d'
down_revision = 'b7340a6c3ecf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('houses', 'external_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('houses', 'external_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
