"""empty message

Revision ID: 302c42a35933
Revises: a10293f5ced8
Create Date: 2022-01-25 01:48:05.875113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '302c42a35933'
down_revision = 'a10293f5ced8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('houses', sa.Column('built_area', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('houses', 'built_area')
    # ### end Alembic commands ###
