"""empty message

Revision ID: 3df8a99f3252
Revises: 5fca0b2536e9
Create Date: 2022-02-12 23:09:26.616532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3df8a99f3252'
down_revision = '5fca0b2536e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cities', sa.Column('ready_to_updates', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cities', 'ready_to_updates')
    # ### end Alembic commands ###
