"""empty message

Revision ID: 67476c41145b
Revises: 302c42a35933
Create Date: 2022-01-25 01:51:06.494550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67476c41145b'
down_revision = '302c42a35933'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('houses', 'external_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('houses', 'external_id',
               existing_type=sa.String(length=255),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
