"""empty message

Revision ID: 874e469f40de
Revises: 70488d0136c5
Create Date: 2022-01-13 01:52:26.288463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '874e469f40de'
down_revision = '70488d0136c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subregions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('subregion_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subregion_id'], ['subregions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('houses', sa.Column('city_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'houses', 'cities', ['city_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'houses', type_='foreignkey')
    op.drop_column('houses', 'city_id')
    op.drop_table('cities')
    op.drop_table('subregions')
    op.drop_table('regions')
    # ### end Alembic commands ###
