"""empty message

Revision ID: 9351b443388f
Revises: 874e469f40de
Create Date: 2022-01-13 11:54:41.156298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9351b443388f'
down_revision = '874e469f40de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cities', sa.Column('external_id', sa.Integer(), nullable=False))
    op.add_column('regions', sa.Column('external_id', sa.Integer(), nullable=False))
    op.add_column('subregions', sa.Column('external_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subregions', 'external_id')
    op.drop_column('regions', 'external_id')
    op.drop_column('cities', 'external_id')
    # ### end Alembic commands ###
